[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/api/*"
  to = "http://159.89.151.109:3000/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/work"
  to = "/work/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false

